<p>You're about to begin your learning journey on programming. You've always been interested about dev (and definitely not the logic of being lazy you took quite seriously).</p>

<p>It's time to start your programmer career! What will you start with?</p>

<form method="get" action="index.php">
    <label for="position">
        <button name="position" value=1>
            Start by understanding the algorithmic logics
        </button>
        
        <button name="position" value=2>
            Ask Chatgpt for the answer (why is this even an option)
        </button>
        
        <button name="position" value=3>
            Start by learning how to make a website (html/css)
        </button>
    </label>
</form>