<p>You start very strongly by trying yourself at the algorithmic logic. In the process, you decide to try out Python as your researches said it was the easiest to start with.</p>

<p>You feel you've got better at understanding how a computer works and feel more confident in tackling other languages!</p>

<p>What will you do next?</p>

<form method="get" action="index.php">
    <label for="position">
        <button name="position" value=4>
            Tackle languages one by one
        </button>
        
        <button name="position" value=5>
            LEARN COBALT AND GET RICH EASILY
        </button>
        
        <button name="position" value=6>
            Start a project to guide your learning journey
        </button>
    </label>
</form>