<h2>Okay you kind of stink for this...</h2>

<p>You follow the saying "a good programmer is a lazy one" a bit too directly and proceed to create ANYTHING using ChatGPT.</p>

<p>As you use more and more water for each prompt, companies get disappointed by you. Sure the output can sometimes look great but all dreams fall apart when looking into the code...</p>

<p>One by one, the companies blacklist you as another "generic ai slop machine" and you fail to find a job instead relying on Grok.</p>

<p>"@Grok is this true?" (bad ending)</p>