<h2>You always wanted to make a game! Surely there are guides around to help you make one...</h2>

<p>You stumble across a 12 HOUR LONG TUTORIAL ON UNREAL ENGINE 5 (yes this is real: https://youtu.be/6UlU_FsicK8) and decide to follow it.</p>

<p>While hour 1 goes okay, you find yourself struggling as the guide seem to assume you have a certain logic of coding. You copy and paste what they show on screen but end not learning anything...</p>

<p>Maybe this isn't the best way to begin your journey</p>