<p>You start learning the most common programming languages one by one. Once you've seen one, you've seen them all you feel despite the changes between each of them.</p>

<p>You end up pulling off a diploma as Full stack developer and see yourself thrown into the working world. Without any project or anything that differentiates you from others, you blend in with the mass of devs...</p>

<p>At least you got to learn what you wanted, right? (neutral ending)</p>