<h2>Yeah sure buddy I'd like to see you tr-</h2>

<p>With the power of spite, plot protection and those programmer socks you were advised to get on Reddit, you manage to learn the Cobalt language and proceed to taunt the narrator. The banks call you and you end up with a strong salary for the rest of your days.</p>

<p>Look I know they say it comes with hard work and all that but that's just unrealistic -_- (unrealistic ending)</p>