<h2>You always wanted to make a game and now seems like the right time for you!</h2>

<p>Project by project, idea by idea, you start to learn the languages you need to achieve your goals while practicing them directly.</p>

<p>You may not have an official diploma, but your Github is filled with projects of all sorts and of all languages. Eventually, some companies notice you and offer you a job. Your career goes smoothly as you gain popularity with your works!</p>

<p>You succeed where others fail and manage to make a name of your own on the internet. (good ending)</p>