<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>Average dev journey</title>
        <link rel="stylesheet" href="styles/layout.css">
    </head>

    
    <body>
        <header>
            <h1>Average dev journey</h1>
        </header>

        <?php require "partials/" . set_position() . ".phtml" ?>

        <footer>
            <a href="index.php?position=0">Start over</a>
        </footer>
    </body>
</html>